let num = 3;
alert(num);
let str ="Привет, Мир!";
document.write(str + '<br>');
let str1 = 'Привет, ';
let str2 = 'Мир!';
document.write(str1 + str2 + '<br>');
let name = 'Ольга';
document.write(str1 + name + '!' + '<br>');
let age = 18;
document.write('Мне ' + age + ' лет!' + '<br>');
let pername;
pername = prompt(pername);
alert('Ваше имя '+ pername);
let number;
number = prompt(number);
alert(number**2);
let Str = 'abcde';
document.write(Str[0] +' '+ Str[2] + ' '+ Str[4] + '<br>');
let num1 = 1000+20*10;
let array = String(num1).split('');
let mult_num = array[0]*array[1]*array[2]*array[3];
document.write(mult_num+'<br>');
let arr = ['a','b','c'];
alert(arr);
document.write(arr[0] +' '+ arr[1] + ' '+ arr[2] + '<br>');
let arr1 = ['a','b','c','d'];
document.write(arr1[0]+'+'+arr1[1]+", "+arr1[2]+'+'+arr1[3]+'<br>');
let arr2 = [2,5,3,9];
let result = (arr2[0]*arr2[1])+(arr2[2]*arr2[3]);
document.write(result+'<br>');
var obj = {a: 1, b: 2, c: 3};
document.write(obj["c"]+"<br>");
document.write(obj.c + '<br>');
var obj = {Коля: '1000', Вася: '500', Петя: '200'};
document.write(obj.Петя + '<br>');
document.write(obj.Коля + '<br>');
var obj = {1:'Понедельник', 2:'Вторник', 3:'Среда', 4:'Четверг', 5:'Пятница', 6:'Суббота', 7:'Воскресенье'};
document.write(obj[1] + '<br>');
let day = 3;
document.write(obj[day] + '<br>');


